[pytest]

addopts = -v -s

markers =
    performance
    skip_in_ci
    crypto


DJANGO_SETTINGS_MODULE = coronavstech.settings
pythonpath = api/coronavstech
python_files = tests.py test_*.py *_tests.py

