name: Django CI

on: [push, pull_request] # Запускать при каждом пуше

jobs:
  test:
    runs-on: ubuntu-latest # Используем Linux-сервер GitHub

    services:
      # Если нужна реальная БД (Postgres), она описывается здесь. 
      # Для SQLite (по умолчанию в Django) этот блок не нужен.

    steps:
      - uses: actions/checkout@v4 # Копируем код проекта

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Твоя версия Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        # импорт coronavstech.settings будет находиться, потому что PYTHONPATH добавит папку api/coronavstech (в ней лежит пакет coronavstech/).
        # Но это избыточно в вашем проекте  У вас это уже задано в pytest.ini:
        # DJANGO_SETTINGS_MODULE = coronavstech.settings pythonpath = api/coronavstech
        # Поэтому в GitHub Actions можно: либо оставить env (будет работать, но дублирует конфиг),
        # либо не задавать env, и pytest-django сам возьмёт всё из pytest.ini (предпочтительнее).
        env:
          DJANGO_SETTINGS_MODULE: coronavstech.settings
          PYTHONPATH: api/coronavstech
        run: |
          pytest